{% set version = "0.10.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggformula
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggformula_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggformula/ggformula_{{ version }}.tar.gz
  sha256: b26d478e7e38bd9ec51777c14a7e0fef41e2c2742ca202532f0f44dc00d6a91d

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ggforce
    - r-ggplot2 >=3.3
    - r-ggridges
    - r-ggstance >=0.3.4
    - r-labelled
    - r-magrittr
    - r-mosaiccore >=0.7.0
    - r-rlang
    - r-scales
    - r-stringr
    - r-tibble
  run:
    - r-base
    - r-ggforce
    - r-ggplot2 >=3.3
    - r-ggridges
    - r-ggstance >=0.3.4
    - r-labelled
    - r-magrittr
    - r-mosaiccore >=0.7.0
    - r-rlang
    - r-scales
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('ggformula')"           # [not win]
    - "\"%R%\" -e \"library('ggformula')\""  # [win]

about:
  home: https://github.com/ProjectMOSAIC/ggformula
  license: MIT
  summary: Provides a formula interface to 'ggplot2' graphics.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: ggformula
# Title: Formula Interface to the Grammar of Graphics
# Description: Provides a formula interface to 'ggplot2' graphics.
# Type: Package
# Version: 0.9.0
# Authors@R: c( person("Daniel", "Kaplan", email = "kaplan@macalester.edu", role = c("aut")), person("Randall", "Pruim", email = "rpruim@calvin.edu", role = c("aut","cre")) )
# License: MIT + file LICENSE
# LazyData: TRUE
# LazyLoad: TRUE
# Depends: R (>= 3.1), ggplot2 (>= 3.0), ggstance (>= 0.3.1)
# Imports: mosaicCore, rlang, magrittr, tibble, stringr, tidyr, grid
# Suggests: dplyr, lattice, mosaic, mosaicModel, mosaicData, testthat, vdiffr, knitr, rmarkdown, lubridate, survival, broom, scales, maps, maptools, rgeos, sf, purrr, ggthemes
# VignetteBuilder: knitr
# RoxygenNote: 6.1.0
# Encoding: UTF-8
# URL: https://github.com/ProjectMOSAIC/ggformula
# BugReports: https://github.com/ProjectMOSAIC/ggformula/issues
# NeedsCompilation: no
# Packaged: 2018-08-02 02:54:56 UTC; rpruim
# Author: Daniel Kaplan [aut], Randall Pruim [aut, cre]
# Maintainer: Randall Pruim <rpruim@calvin.edu>
# Repository: CRAN
# Date/Publication: 2018-08-03 17:10:02 UTC
