{% set version = "0.12.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggformula
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggformula_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggformula/ggformula_{{ version }}.tar.gz
  sha256: d569f83e059f9e4836bd513f92706fb8a614300f744dcc47bf86e8dafd8e776d

build:
  noarch: generic
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-ggplot2 >=3.3
    - r-ggridges
    - r-labelled
    - r-mosaiccore >=0.7.0
    - r-rlang
    - r-scales
    - r-stringr
    - r-tibble
  run:
    - r-base
    - r-ggplot2 >=3.3
    - r-ggridges
    - r-labelled
    - r-mosaiccore >=0.7.0
    - r-rlang
    - r-scales
    - r-stringr
    - r-tibble

test:
  commands:
    - $R -e "library('ggformula')"           # [not win]
    - "\"%R%\" -e \"library('ggformula')\""  # [win]

about:
  home: https://github.com/ProjectMOSAIC/ggformula
  license: MIT
  summary: Provides a formula interface to 'ggplot2' graphics.
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor
