appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: ck34uhQTfZFm97ub0rj2T89sW4mnKZ3tM22NUwGoRmHU/1621CsXy0OSe65LdR5vbt3HWMcgD3HoB+lFBeKOoR9RQaYMLsBDaJucjaaoMQJC8txwgyEjaZrzBpqFUkkPr7/HCy50/QnxXiwvnT8gFfF5lt5FSBKYNfxFp52NkmvondhJ1F3IU3XrMTGC6X5GG9ix841/SFlGBswWuQdzHS42JadRC7w/SsXtJZCXuQ+gJDNBSt+h+ey24SeNLtYA9AhNqI41juAfMNDeUc5uU+48KG54wniOcQfyQr0UYgydmWQ6zh4eqNeWaFuR/KMSSy4AJ0j+Y6zBVgVVX4hEZLA1ANoebSQvTTvrwhmODAKiT3W02XSfHm8h6ndwi1WjBOLdL6kN5aVh6mgwsLO0h00yOCwWxTCgOGmkzT0v+r8z75fWevIoqhQdqfdRJHrEj24RO2ev9A6hebdVWBmxSkHXTC35rfS8VaXnwEObsr9I0oFoI3NuRsX7E1iDS05LF9FHODCL1EPQMXW3CdeaCZ8V69fuZS/o407xey2n4pQduzfkNKfnR0eJyaq/BhTSF6hP7Bk0E9Q1nz+GbE00P82DArWvRWtJLHzaxEOrP1qwcd7Ibz3c+9KCfz7hye/ubhTJN1dF3Y9LkmipBTgsv/61jr0MAd6um4EwtVgOBcI=
